# Generated by Django 5.1.6 on 2025-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_patient_emailid_patientcredientialsmodel_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctortId', models.AutoField(primary_key=True, serialize=False)),
                ('doctorName', models.CharField(max_length=40)),
                ('doctorEmail', models.CharField(max_length=100)),
                ('doctorPhoneNo', models.IntegerField(max_length=12)),
                ('SpecilizedIn', models.CharField(max_length=50)),
                ('patientPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=40)),
                ('patientEmail', models.CharField(max_length=100)),
                ('patientPhoneNo', models.IntegerField(max_length=12)),
                ('patientPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientCredientialsModel',
        ),
    ]
