# Generated by Django 5.1.6 on 2025-02-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_doctor_patient_delete_patientcredientialsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='patientPassword',
            new_name='doctorPassword',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='SpecilizedIn',
            new_name='specializedIn',
        ),
    ]
