# Generated by Django 5.1.6 on 2025-02-28 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('mailId', models.AutoField(primary_key=True, serialize=False)),
                ('senderEmail', models.CharField(max_length=200)),
                ('senderName', models.CharField(max_length=30)),
                ('recevierEmail', models.CharField(max_length=200)),
                ('recevierName', models.CharField(max_length=30)),
                ('mailBody', models.CharField(max_length=500)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
