# Generated by Django 5.1.6 on 2025-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('user_query', models.CharField(max_length=300)),
                ('user_uploadedFile', models.FileField(upload_to='')),
            ],
        ),
    ]
