# Generated by Django 5.1.6 on 2025-02-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user_uploadedFile',
            field=models.ImageField(upload_to='media/disease'),
        ),
    ]
