# Generated by Django 5.1.6 on 2025-02-21 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usermessage_user_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointement',
            fields=[
                ('appointementId', models.AutoField(primary_key=True, serialize=False)),
                ('appointementFor', models.CharField(max_length=100)),
                ('doctorName', models.CharField(max_length=40)),
                ('patientName', models.CharField(max_length=40)),
                ('appointmentTime', models.CharField(max_length=40)),
                ('appointmentDate', models.CharField(max_length=40)),
                ('appointementStatus', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserMessage',
            new_name='UserQuery',
        ),
    ]
