# Generated by Django 5.1.6 on 2025-02-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointement_rename_usermessage_userquery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointement',
            new_name='Appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointementId',
            new_name='appointmentId',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointementStatus',
            new_name='appoitementStatus',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentDate',
            new_name='appoitmentDate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentTime',
            new_name='appoitmentTime',
        ),
    ]
