# Generated by Django 5.1.6 on 2025-02-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_appointement_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appoitementStatus',
            new_name='appointementStatus',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appoitmentDate',
            new_name='appointmentDate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appoitmentTime',
            new_name='appointmentTime',
        ),
    ]
