# Generated by Django 5.1.6 on 2025-03-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_appointementfor_appointment_appointmentfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientEmail',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientPhoneNo',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
