# Generated by Django 5.1.6 on 2025-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_appointment_patientemail_appointment_patientphoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientEmail',
            field=models.CharField(default='test@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientPhoneNo',
            field=models.CharField(default='9006552672', max_length=10),
        ),
    ]
