# Generated by Django 5.1.6 on 2025-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_appointment_patientemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientEmail',
            field=models.CharField(default='test@gmail.com', max_length=200, null=True),
        ),
    ]
