# Generated by Django 5.1.6 on 2025-03-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_appointment_patientemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientEmail',
            field=models.EmailField(blank=True, default='', max_length=200, null=True),
        ),
    ]
