# Generated by Django 5.1.6 on 2025-03-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_appointment_patientemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientEmail',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientPhoneNo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
