# Generated by Django 5.1.6 on 2025-03-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_appointment_patientemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctorEmail',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
