# Generated by Django 5.1.6 on 2025-03-02 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_appointment_doctoremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentGrant',
            fields=[
                ('appointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('treatmentFor', models.CharField(max_length=100)),
                ('patientName', models.CharField(max_length=40)),
                ('patientEmail', models.EmailField(default='', max_length=200)),
                ('patientPhoneNo', models.CharField(default='', max_length=10)),
                ('appointmentTime', models.CharField(max_length=40)),
                ('appointmentDate', models.CharField(max_length=40)),
                ('appointementStatus', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
