# Generated by Django 5.1.6 on 2025-03-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_appointmentgrant_messagefromdoctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentgrant',
            old_name='appointmentTime',
            new_name='appointmentDateTime',
        ),
        migrations.RenameField(
            model_name='appointmentgrant',
            old_name='appointmentDate',
            new_name='appointmentGrantDateTime',
        ),
    ]
